services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data/db:/var/www/backend/var/db
      - app-public:/var/www/backend/public
    entrypoint: ["/bin/bash", "/var/www/backend/docker-entrypoint.sh"]
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: sqlite:///%kernel.project_dir%/var/db/data.db
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWORD: changeme

  nginx:
    image: nginx:stable
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app-public:/var/www/backend/public:ro
    depends_on:
      - php

volumes:
  app-public:
