services:
  pocketmoney:
    image: ghcr.io/neriderc/pocketmoney:latest
    ports:
      - "8000:80"
    volumes:
      - ./data/db:/var/www/backend/var/db
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: sqlite:///%kernel.project_dir%/var/db/data.db
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWORD: changeme
      DOMAIN: example.com
