services:
  pocketmoney:
    image: ghcr.io/neriderc/pocketmoney:latest
    volumes:
      - ./data/db:/var/www/backend/var/db
      - app-public:/var/www/backend/public
    entrypoint: ["/bin/bash", "/var/www/backend/docker-entrypoint.sh"]
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      DATABASE_URL: sqlite:///%kernel.project_dir%/var/db/data.db
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWORD: changeme

  nginx:
    image: nginx:stable
    ports:
      - "8000:80"
    volumes:
      - app-public:/var/www/backend/public:ro
    depends_on:
      - pocketmoney
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf

volumes:
  app-public:

configs:
  nginx_conf:
    file: ./nginx/nginx.conf
